ツイート機能作成
shinonome-inc/backend-final-assignment-Tatsuro pull request #3
Opened 2022-08-14 00:44 UTC by tatsurou9003

tweet機能を作成しました、レビューお願いします!

2022-08-14 00:51 UTC, tatsurou9003 commented
![tweet機能テスト](https://user-images.githubusercontent.com/99654281/184518012-4ff83183-1a45-4ed2-a4b4-ba01913f87d6.png)
テストのスクリーンショットを添付しておきます。

2022-08-15 04:07 UTC, kunikida007 commented on tweets/tests.py
>      def test_success_get(self):
テストのメソッド名はtest_get~, test_post~と続いたほうがわかりやすいと思います。

2022-08-15 05:27 UTC, tatsurou9003 commented on tweets/tests.py
>      def test_success_get(self):
確かに！そっちの方が親切で良さそうですね、アドバイスありがとうございます。修正しておきます。

2022-08-15 05:38 UTC, kunikida007 commented on tweets/tests.py
> +    def test__post_success(self):
_が一つ多いです。

2022-08-15 23:54 UTC, TAK848 requested changes
よくできていると思います！！
数点コメントしました！！

2022-08-15 23:54 UTC, tak848 commented on accounts/views.py
> +    context_object_name = "tweet_list"
select_relatedもしっかりしつつ，ListView使いこなせていて良いと思います！

2022-08-15 23:54 UTC, TAK848 commented on tweets/models.py
> +    date_posted = models.DateTimeField(default=timezone.now)
作成日時は`created_at`，更新日時は`updated_at`の方がより一般的かもです

ちなみに`created_at`は`auto_now_add`，`updated_at`は`auto_now`を使用できます

2022-08-15 23:54 UTC, TAK848 commented on tweets/tests.py
> +CustomUser = get_user_model()
（今回より前の範囲なのでスルーでOKです）`CustomUser`とか気にしなくて良いように吸収するための`get_user_model`なので，単に`User=`で良いかもです

2022-08-15 23:54 UTC, TAK848 commented on tweets/views.py
> +
他と合わせて空行消しときましょう（統一して空けても良いです）

2022-08-15 23:54 UTC, TAK848 commented on tweets/views.py
> +    # ログインユーザーと結びつけてるのは分かったがinstanceの意味がよくわからん
formのinstanceは，formが扱っている（=CreateViewで作っているモデルの）オブジェクトを指します
今回で言うと，form_validまでで構築したTweetのobject

そのuserfieldに，formからのリクエストだけではつけれないuser情報を付加してる感じですね

（コメント消しときましょう！）

2022-08-15 23:54 UTC, TAK848 commented on tweets/views.py
> +# from django.http import Http404
delete

2022-08-15 23:54 UTC, TAK848 commented on tweets/views.py
> +    #  user = self.request.userとしてreturn user.pk == self.kwargs['pk']ではダメっぽい？・・・
model=Tweetなので，pkはTweetのpkであり，userのpkと比較しても意味がありません（たまたま重複することはあると思います）

（コメント消しときましょう！）

2022-08-15 23:54 UTC, TAK848 commented on tweets/tests.py
> +        self.client.force_login(self.user2)
self.user2->user2でOkです（このメソッドでしか使っていない）
ここでもう一度client.force_loginし直すよりは，Tweetをuser2で作った方が簡潔になると思います

あと意味を明確にするために，user，another_userとかの命名にするとより良いです

2022-08-16 01:30 UTC, tatsurou9003 commented on accounts/views.py
> +    context_object_name = "tweet_list"
あざます！

2022-08-16 01:47 UTC, tatsurou9003 commented on tweets/views.py
> +    #  user = self.request.userとしてreturn user.pk == self.kwargs['pk']ではダメっぽい？・・・
確かに！よく考えたらその通りですね

2022-08-16 01:48 UTC, tatsurou9003 commented on tweets/views.py
> +    # ログインユーザーと結びつけてるのは分かったがinstanceの意味がよくわからん
なるほど、助かります！

2022-08-16 02:19 UTC, tatsurou9003 commented on tweets/models.py
> +    date_posted = models.DateTimeField(default=timezone.now)
了解です！created_atに変更、auto_now_addを使用するように変更します。

2022-08-16 02:22 UTC, tatsurou9003 commented on tweets/tests.py
> +        self.client.force_login(self.user2)
了解です！user2でtweetを作成、userがそのままログインした状態でuser2のtweetをdeleteさせるよう変更します。

2022-08-16 02:44 UTC, TAK848 commented on tweets/tests.py
> +        self.client.force_login(self.user2)
self.userとself.user2にするなら，self.user1とself.user2の方が良いかもです

2022-08-16 02:51 UTC, TAK848 commented on tweets/migrations/0001_initial.py
> +    ]
一度migrationを削除し反映させたっぽいですが，これすると今使ってるDBのデータをmigrate前に一旦ロールバックしてから反映という手間を踏む必要があり，最悪つまづきます（多分ローカルのdbを一旦削除する手間を踏んだと思います）。
今回はまだマージ前のものの編集なので本番環境に未反映のものの編集ということで（案件なら）OKですが，既にマージされたmigrationファイルは絶対に編集しないように気をつけましょう！

（パフォーマンス上げる目的の対処法もありますし，ローカルでの開発も大変になるので，無理に削除，編集はあまりお勧めしません。ただし，migrationファイルを修正しまくって10個も20個も作っちゃった…って時はやった方が良いかも）

2022-08-16 02:55 UTC, TAK848 approved these changes
LGTM！！

2022-08-16 02:56 UTC, merged