Follow機能作成
shinonome-inc/backend-final-assignment-Tatsuro pull request #4
Opened 2022-09-02 10:26 UTC by tatsurou9003

Follow・Unfollow機能を作成しました。
・プロフィール機能を作成していないためツイート詳細・フォロワーリスト画面からフォローする仕様です。
・ログインユーザーのフォローリスト・フォロワーリストしか見ることが出来ません。いいね機能作成後プロフィール機能作成時に修正しようと考えていますが、ご意見があれば頂きたいです。

2022-09-02 10:27 UTC, tatsurou9003 commented
![フォロー機能test](https://user-images.githubusercontent.com/99654281/188120225-6f8af37f-d519-437c-a551-5bb2b06127f1.png)
テスト成功時のスクリーンショットを添付しておきます。

2022-09-05 05:35 UTC, fujinomoto62 commented
一次レビューLGTMです。要件は満たせていると思います。
importで内部と外部で分けられていて良いと思います。

2022-09-07 05:07 UTC, TAK848 requested changes

2022-09-07 05:07 UTC, tak848 commented on accounts/models.py
> +        return f"{self.follower}follow{self.following}"
modelにもUniqueConstraintをつけておきましょう

2022-09-07 05:07 UTC, tak848 commented on accounts/urls.py
> +# path("profile/", views.UserProfileView.as_view(), name="user_profile"),
Profileモデルはいらないですが，UserのDetailViewとして作成しましょう（ここにfollowing_listなども貼れば良いです！）

2022-09-07 05:07 UTC, tak848 commented on accounts/views.py
> +            raise Http404
tryの範囲が広すぎてどこでのエラー想定かわからないので，tryで囲う行はエラーが出る可能性のある部分だけにしてください

※messagesを使わないのであれば，get_object_or_404を使えますね

2022-09-07 05:07 UTC, tak848 commented on templates/accounts/follow.html
> +{% endif %}
messagesはbase.htmlに貼って良いと思います（こうすると他のviewでも確認できます）

2022-09-07 05:20 UTC, TAK848 commented on templates/tweets/tweet_detail.html
> +<small><a href="{% url 'accounts:follow' tweet.user.username %}">Follow</a></small>
followしてる人に対してはunfollowボタンに変えてください！

2022-09-23 18:44 UTC, tatsurou9003 commented
ProfileのtemplateからFollowできるように仕様を変更。FollowとUnfollowのtemplate要らなくなったから削除したぞ。

2022-09-25 01:43 UTC, TAK848 requested changes
よくできてると思います！！
3点だけお願いします！！

2022-09-25 01:43 UTC, TAK848 commented on accounts/models.py
> +        return str(self.user)
このモデル自体は使ってないので消しましょう！（introduction足したかったらCustomUserモデルに足せば良いです！）

2022-09-25 01:43 UTC, TAK848 commented on accounts/views.py
> +class FollowingListView(LoginRequiredMixin, ListView):
これ現状ListViewの機能を使っていないので`TemplateView`でOKです！

※ListViewをもし使うとなると，get_querysetやcontext_object_nameをいじるなどしてfilter処理などを挟んであげる必要があります

2022-09-25 01:43 UTC, TAK848 commented on accounts/views.py
> +# class ProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
コメント消しときましょう！

2022-09-25 04:55 UTC, TAK848 approved these changes
LGTM!!

2022-09-25 04:55 UTC, merged